### PR TITLE
Automatically split up test files in parallel CI jobs

### PR DESCRIPTION
**Pull request by jamiebuilds**
Starting point for #1811

### CODE REVIEW

**Comment by jamiebuilds** [comment]
Awesome, thanks. I'll look into doing that today

**Comment by jamiebuilds** [comment]
Actually, the one big problem with the hash approach is that it creates surprising groupings of tests.

It seems reasonable to expect tests in the same sub-directory to be mostly in one job instead of distributed across all of them.

What if we sorted the files ourselves instead? It'll be faster than creating hashes, especially since we can expect them to already be in a decently sorted starting state.

**Comment by jamiebuilds** [comment]
Updated

**Comment by harrysarson** [comment]
I had a look at https://github.com/hughsk/path-sort which is the dependancy added in this Pr.

There is a pull request there that has been open for a year without any response so I dunno if the package is maintained at all.

Just thought I should flag this up, I like the idea of split tests though :)

**Comment by novemberborn** [comment]
> Actually, the one big problem with the hash approach is that it creates surprising groupings of tests.
> 
> It seems reasonable to expect tests in the same sub-directory to be mostly in one job instead of distributed across all of them.

@jamiebuilds I don't know if that's such a big problem. Even with sorting there is no guarantee of sensible grouping.

> I had a look at hughsk/path-sort which is the dependancy added in this Pr.
> 
> There is a pull request there that has been open for a year without any response so I dunno if the package is maintained at all.

I'd be happy to use lexical sort and not use a dependency at all.

**Comment by jamiebuilds** [comment]
> Even with sorting there is no guarantee of sensible grouping.

Yeah, it might not be perfect, but we do this with Jest today and it is nicer than a completely random grouping.

We can even improve upon this and find a reliable way to keep folders together even when it distributes them unevenly.

> > I had a look at hughsk/path-sort which is the dependancy added in this Pr.
> > 
> > There is a pull request there that has been open for a year without any response so I dunno if the package is maintained at all.
> 
> I'd be happy to use lexical sort and not use a dependency at all.

I used it because otherwise it completely changes the order that Ava runs tests. Right now the way it discovers files recursively is already giving us files ordered by their directories.

I'm happy to fork `path-sort` and maintain it. I'll reach out to the original author about it

**Comment by jamiebuilds** [comment]
Alternatively, Ava might want to implement a randomized order feature like in [RSpec](https://relishapp.com/rspec/rspec-core/docs/command-line/order).

**Comment by novemberborn** [comment]
@jamiebuilds I've pushed some updates. Notably, the distribution algorithm has been changed. I didn't really like the floating point arithmetic. If I've figured out the maths correctly then earlier jobs will run 1 extra file each compared to later jobs. This leads to a nice predictable distribution.

Regarding `path-sort2`, why can't we rely on `Array<string>#sort()`?

We still need test coverage before we can land this. If you happen to have a project set up in CI you could test this with that'd be great too (in addition to the test coverage), just to get some confirmation it all works as expected.

**Comment by novemberborn** [comment]
Yes.

Also, and I'll try and do this today, I think we should pass the `index` and `total` values as parameters to the `Api` constructor, and resolve them in `lib/cli`. That way there is no unexpected behavior when using `ava/api` directly (not that that's officially supported, but hey).

**Comment by jamiebuilds** [comment]
`Array<string>#sort()` does produce a different order, nothing terribly dramatic though. In a single folder, files and sub-folders are mixed together:

- `file-dir-file-dir` `Array<string>#sort()` 
- `file-file-dir-dir` `pathSort()`

**Comment by jamiebuilds** [comment]
If you do end up using `#sort()`, I would make sure it is case-insensitive:

```js
files.sort((a, b) => {
  return a.toUpperCase().localeCompare(b.toUpperCase());
});
```

**Comment by novemberborn** [comment]
@jamiebuilds @sindresorhus I think this is ready now:

* CLI determines whether parallel runs are enabled, not `Api`
* I've removed `path-sort2`
* I've added documentation
* I've added an integration test

I've temporarily included #1874 which ensures integration tests actually run…

**Comment by jamiebuilds** [comment]
Thank you so much for getting this in 😄

**Comment by novemberborn** [comment]
@jamiebuilds thanks for the suggestion, kicking it off, and your patience! 😄

**Pull request merged**
