### PR TITLE
Center the logo in the readme

### PR DESCRIPTION
**Pull request by Illu**
Small adjustment to the readme, it looks better imho 😉

### CODE REVIEW

**Comment by novemberborn** [comment]
Sure, not opposed to this. Though I'm not 100% sure how this would render on npm. Do you know of any other packages that use this kind of markup?

**Comment by Illu** [comment]
You're right, I tried it with one of my packages and it doesn't seem to render correctly on npm. I'm closing this PR.

**Comment by sindresorhus** [comment]
We should not care how it renders on npm. Their Markdown rendering is not good anyway.

**Comment by novemberborn** [comment]
@Illu when you say it didn't render correctly, do you mean it wasn't centered, or it didn't show up / HTML tags were visible?

**Comment by Illu** [comment]
@novemberborn the logo didn't show up at all. However, I found [this package](https://www.npmjs.com/package/@nozbe/watermelondb) that uses the same kind of markup to render its logo.

**Comment by novemberborn** [comment]
@Illu that uses:

```html
<p align="center">
  <img src="https://github.com/Nozbe/WatermelonDB/raw/master/assets/logo-horizontal2.png" alt="WatermelonDB" width="539" />
</p>
```

We could put something like that at the top of the README. @gurrrung opened https://github.com/avajs/ava/pull/2214 which wraps that in an H1. I wonder if that would work?

**Comment by novemberborn** [comment]
Closing due to inactivity. We'd be happy to pick this up again when you have the time to get back to this.

**Pull request closed without merging**
