### PR TITLE
Fix ObservableLike interface

### PR DESCRIPTION
**Pull request by bigslycat**
`subscribe` method of `ObservableLike` is incompatible with ES Observable `subscribe` method: https://github.com/tc39/proposal-observable#observable

I fix it in this PR. Before, I forced to annotate `test` callbacks like:

```js
test('Subject', (t): any => {
  ...
```

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you add a test [here](https://github.com/avajs/ava/tree/master/test/flow-types) and [here](https://github.com/avajs/ava/tree/master/test/ts-types)?

**Comment by sindresorhus** [comment]
Your indentation is off. Make sure you use tab-indentation.

**Comment by sindresorhus** [comment]
@bigslycat Ping :)

**Comment by bigslycat** [comment]
@sindresorhus sry, forgot about this. I'll finish it tomorrow.

**Comment by sindresorhus** [comment]
Ping @bigslycat :)

**Comment by sindresorhus** [comment]
Closing for lack of response. Happy to reopen if you ever get to this ;)

**Pull request closed without merging**
