### PR TITLE
Use `diff-match-patch` for text diffs

### PR DESCRIPTION
**Pull request by lukechilds**
Resolves https://github.com/avajs/ava/issues/1280

`diff` is really slow for large strings. This just swaps out the `diff` npm package for `diff-match-patch` which is waaaay quicker. Down from ~20mins to ~1.5s in the linked issue.

### CODE REVIEW

**Comment by vadimdemedes** [comment]
Thanks for submitting such an easy-win PR, love it! Obviously, I'm all for perf optimization, especially with such a little change. However, this module seems to be unmaintained. The last commit is from 2015, despite having open issues and PRs. 

Perhaps you are aware of some alternatives?

Also, can we swap the usage of 'diff' to the other library, so that we don't have 2 dependencies that basically do the same thing?

**Comment by lukechilds** [comment]
Ah, I chose that module as it was recommended in the issue: https://github.com/avajs/ava/issues/1280#issuecomment-282258975

Didn't realise it was unmaintained, I'll have a look for some others.

> Also, can we swap the usage of 'diff' to the other library, so that we don't have 2 dependencies that basically do the same thing?

Only if it supports generating a patch. The `diff` lib was being used to generate a diff for strings and a patch for arrays/objects.

**Comment by vadimdemedes** [comment]
Well, if there are no viable and just-as-fast diff libraries out there, we can go with this one at least for string diffs, I think. It's better to use this library, than to have 20m of waiting time.

**Comment by lukechilds** [comment]
The only other I've found is: https://github.com/liddiard/text-diff

It's also pretty outdated and is just a wrapper around the same Google lib that the other project is a clone of: https://code.google.com/p/google-diff-match-patch/

**Comment by vadimdemedes** [comment]
This one doesn't have tests, so it's not a good candidate. Ok, so I see there aren't that many diff libs out there, I think we may just go with the one you used in the PR. I will test how it works and what output it provides, thank you!

**Comment by lukechilds** [comment]
No probs 👍

**Comment by lukechilds** [comment]
Is it not already fixed in https://github.com/avajs/ava/pull/1285/commits/d402277ed8670eec5a4276ff9236d12589046959?

**Comment by lukechilds** [comment]
@novemberborn Is it not already fixed in https://github.com/avajs/ava/pull/1285/commits/d402277ed8670eec5a4276ff9236d12589046959?

**Comment by novemberborn** [comment]
Oh interesting. My merge button was set to *Rebase and merge*, which can't work, but I *can* squash and merge.

**Comment by novemberborn** [comment]
Thanks @lukechilds!

**Comment by lukechilds** [comment]
I like to call that squirging. No problem 👍

**Comment by leoswing** [comment]
> I like to call that squirging. No problem 👍

Does the google diff generate a patch? which it could be used for diff2html and produce a nice diff like git diff

**Pull request merged**
