### PR TITLE
Experimentally disable null expectations for throws assertions

### PR DESCRIPTION
**Pull request by JSimoni42**
Aims to fix https://github.com/avajs/ava/issues/2410

### CODE REVIEW

**Review by novemberborn — COMMENTED** [review]
Thanks for picking this up @JSimoni42!

**Comment by novemberborn** [comment]
Awesome.

What's left now is to update the documentation:

* https://github.com/avajs/ava/blob/master/docs/03-assertions.md#throwsfn-expectation-message
* https://github.com/avajs/ava/blob/master/docs/03-assertions.md#throwsasyncthrower-expectation-message

In both those places it says you need to specify `null`. Since we now allow `undefined` as well let's just recommend that. And then we can say something in parentheses like:

> (AVA 3 also allows you to specify `null`. This will be removed in AVA 4. You can opt in to this change early by enabling the `disableNullExpectations` experiment.)

**Comment by JSimoni42** [comment]
@novemberborn Documentation has been updated. I noticed that https://github.com/avajs/ava/pull/2575 was also failing checks due to the same test error in `Install and test AVA / Node.js (^14.0.0, ubuntu-latest)`. Suffice it to say, it seems like this PR didn't introduce any additional test failures. Let me know if I should squash/merge or if you'd prefer to handle that, yourself

**Comment by novemberborn** [comment]
> Let me know if I should squash/merge or if you'd prefer to handle that, yourself

Should be fine now…

**Comment by novemberborn** [comment]
Thanks @JSimoni42!

**Pull request merged**
