### PR TITLE
Document context support in before & after hooks

### LINKED ISSUE #1579: Allow context in before hook
It would be useful to have context available in `before` hooks, so that messy workarounds like in https://github.com/avajs/ava/issues/1542 aren't required. It's useful in cases where you're doing integration testing and are downloading several URLs whose content will be used across multiple tests.

Without being able to share context in before hooks you would need to resort to the workaround, or download the page for each test each time, even though the content doesn't change between tests.

### PR DESCRIPTION
**Pull request by novemberborn**
Fixes #1579.

Heads up @kugtong33.

### CODE REVIEW

**Comment by kugtong33** [comment]
:+1: , I was heading on creating a PR for this, should I reference it still? :D

**Comment by novemberborn** [comment]
@kugtong33 looks like I beat you to it, sorry. Wanted to get this in so I can do a new release. Let me know if there's anything you'd like to see changed in my version though.

**Comment by kugtong33** [comment]
@novemberborn , I think the important part is to determine what values are shared/referenced and what values are independent in each test, and better examples would be fine, as I have added on my side we can give examples for referenced values and primitive values and how they can use contexts correctly.

We can also create a recipe for it, migrating declared variables outside of hooks into using contexts. On my side, I am heavily using `supertest` and I would love to try to use contexts on passing `supertest` responses from hooks to tests.

**Comment by novemberborn** [comment]
@kugtong33 a recipe would be good. It's too much to capture in the README itself.

**Pull request merged**
