### PR TITLE
Bump XO and fix some lint issues

### PR DESCRIPTION
**Pull request by sindresorhus**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Any idea why Travis is failing? It's passing for me locally...

**Comment by novemberborn** [comment]
Not sure, perhaps something to do with `npm link` or your local setup that changes the ESLint rules for that file? Could disabling ESLint altogether maybe, just in that file.

**Comment by kevva** [comment]
Don't think it's specific to @sindresorhus local environment. Passes locally for me too.

**Comment by novemberborn** [comment]
Yup that fixed it. Remaining failure because npm@6.6.0 churns the lockfile. Will address that separately.

**Pull request merged**
