### PR TITLE
add t.notRegex

### LINKED ISSUE #877: t.notRegex
Using `t.false(/regex/.test(str))` feels inconsistent.

### PR DESCRIPTION
**Pull request by jamestalmage**
Fixes #877

### CODE REVIEW

**Comment by jamestalmage** [comment]
I cancelled the AppVeyor run, because I want to get a patch release out ASAP, and didn't want to wait for this.

**Comment by nfcampos** [comment]
don't you need to add it here https://github.com/avajs/ava/blob/master/lib/enhance-assert.js#L6 ?

**Comment by jamestalmage** [comment]
Indeed. Thanks.

**Comment by sindresorhus** [comment]
:shipit:

**Comment by jfmengels** [comment]
Cool! We need to add it to the linter too. I'll do it tonight except if someone wants to beat me to it ;)

**Pull request merged**
