### PR TITLE
[typescript] added missing todo definition

### PR DESCRIPTION
**Pull request by andischerer**
Hey guys,
first of all thanks for this awesome testrunner.

I've added the missing todo definition to the index.d.ts.

### CODE REVIEW

**Comment by jamestalmage** [comment]
@SamVerschueren

**Comment by sindresorhus** [comment]
We also need to add `test.failing`. Anything else that needs updating?

**Comment by sindresorhus** [comment]
// @ivogabe

**Comment by jamestalmage** [comment]
It would be good to land this as part of the upcoming release as well.

**Comment by ivogabe** [comment]
Does `todo` allow chaining? This definition doesn't allow it.

**Comment by jamestalmage** [comment]
Yes. The only checks against `todo` are [here](https://github.com/avajs/ava/blob/master/lib/runner.js#L112-L121).
  - It can't contain an implementation.
  - It must have a title

**Comment by SamVerschueren** [comment]
Seems ok, not much to it :).

**Comment by jamestalmage** [comment]
@SamVerschueren Does it need something additional to enable chaining?

**Comment by SamVerschueren** [comment]
Yes, this will only allow you to write `test.todo('message')`. But `todo` doesn't allow chaining right?

**Comment by jamestalmage** [comment]
I can't really think of a reason to chain:

```
test.serial.todo
test.after.todo
```

Maybe we should just disallow chaining of `todo` methods.

**Comment by jamestalmage** [comment]
Merging. We can debate what to do about `todo` chaining in #847.

**Comment by sindresorhus** [comment]
@ivogabe @SamVerschueren Could either of you add `test.failing`?

https://github.com/avajs/ava#failing-tests

**Comment by SamVerschueren** [comment]
Yeah sure.

**Comment by jamestalmage** [comment]
While you are at it, I think there's an error when it comes to using `test.serial`. 

`test.serial` tests are allowed to return a promise, or have callbacks.

`test.serial.cb` is totally allowed, as is `test.serial(promiseReturning)`.

The point of `test.serial`, is that it makes the tests run independently without contention. `.serial` tests are run first, and one at a time, whereas the default is to run with max concurrency. They are allowed to be async, via `.cb` or returning a Promise/Observable.

**Comment by SamVerschueren** [comment]
I think you're right (not tested yet). It looks like `test.serial.cb` is not defined.

**Pull request merged**
