### PR TITLE
Add tests for improper-usage-messages

### PR DESCRIPTION
**Pull request by abouthiroppy**
Increase coverage of `reporters/improper-usage-messages.js`.(100%)

### CODE REVIEW

**Comment by abouthiroppy** [comment]
@novemberborn Thank you for your feedback. I saw ava's coverage.(using Istanbul)

I got the following results on my PC.(console output is the same)
This is master branch.


It's strange.🤔

**Comment by novemberborn** [comment]
@abouthiroppy `npm test` gives me the same coverage as on codecov.

**Comment by abouthiroppy** [comment]
@novemberborn hmmm... ok, I'll close this PR. Thanks!

**Comment by novemberborn** [comment]
@abouthiroppy that last `results when nothing is applicable` test still increases the code coverage though. Do you want to reopen the PR so we can land that?

**Comment by abouthiroppy** [comment]
@novemberborn ok, I'll modify the test code;)

**Comment by abouthiroppy** [comment]
`The feature/add-test-for-improper-usage-messages branch was force-pushed or recreated.`
so, I can not reopen this PR.
Sorry, I'll create new PR...

**Pull request closed without merging**
