### PR TITLE
extend --match to support hash (generated from unique title)

### PR DESCRIPTION
**Pull request by timoweave**
extend --match to support hash key, which is generated from title (which ava ensure title to be unique).

Screen Shot 2019-07-25 at 1 42 17 PM

> What problems does this solve?

enhancement (how to add label)?

### CODE REVIEW

**Comment by sindresorhus** [comment]
What problems does this solve?

**Comment by timoweave** [comment]
request enhancement (and for other new flag --ignore, --match, --find
(https://github.com/avajs/ava/issues/1472)

**Comment by novemberborn** [comment]
Hi @timoweave, impressive work on the PR!

To avoid disappointment though, I'd advise filing an issue with your proposal first before doing all the work. As evidenced by @sindresorhus's question above, I don't think this solves an actual problem. It puts more noise in the reporter output and it's not really easier than using `--match` or adding `.only` or `.skip` modifiers inside your test file.

I'm looking forward to other PRs from you though! 😄 

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by timoweave** [comment]
Oh, what kinda feature do you need help on?

**Comment by novemberborn** [comment]
@timoweave have a look at https://github.com/avajs/ava/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A"help+wanted" — there'll be more esoteric issues without that label if you want to venture really deep into the weeds.

**Comment by timoweave** [comment]
Need to prioritize 140 issues...
What are the top 25?

**Comment by novemberborn** [comment]
> Need to prioritize 140 issues...

There's "only" 82 with a help wanted label 😉 https://github.com/avajs/ava/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A"help+wanted"

We don't have a priority list as such, but you could use the [Funded on IssueHunt](https://github.com/avajs/ava/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A"help+wanted"+label%3A"%3Adollar%3A+Funded+on+Issuehunt") labels as a proxy. Bugs tend to be more important to solve than feature requests.

Generally speaking I find it's most fun to solve a problem you run into yourself, or add a feature you would see yourself using. You can also have a look at the `scope:` labels to get a sense of where in the codebase the issue is.

**Comment by timoweave** [comment]
Yeah, it's most fun to solve a problem you run into yourself, or add a feature (but you turn it down last time) you would see yourself using.

**Pull request closed without merging**
