### PR TITLE
Remove t.doesNotThrow - fixes #850

### LINKED ISSUE #850: Remove `t.doesNotThrow`
I noticed that in `master`, `t.doesNotThrow` still exists even though it was deprecated (I didn't even know/remember it existed actually).
There is a link to `ava-codemods` (to be updated too, it points to @jamestalmage's repo), but there is no codemod for it.

I suggest removing it altogether, since it looks like it's been removed for a while now. Either that, or add a new codemod for it at the very least.

Willing to do the PR for the removal and the link fixing, and/or the codemod.

### PR DESCRIPTION
**Pull request by platy11**
Fixes #850

### CODE REVIEW

**Comment by platy11** [comment]
@sindresorhus The tests are failing because they use t.doesNotThrow a lot, I'm not quite sure how to replace this yet

**Comment by sindresorhus** [comment]
Remove this test: https://github.com/avajs/ava/blob/28bb0d5cb2907282d61e224acdf621ce3c1abdfd/test/assert.js#L362-L378

**Comment by platy11** [comment]
@sindresorhus OK, tests now pass

**Comment by sindresorhus** [comment]
Cool. Thank you :) Keep 'em coming 🍻

**Pull request merged**
