### PR TITLE
Add support for `code` in `expected` t.throws() and t.throwsAsync() t…

### PR DESCRIPTION
**Pull request by okyantoro**
Fixes https://github.com/avajs/ava/issues/1901

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you also update the TypeScript and Flow type definitions?

https://github.com/avajs/ava/blob/master/index.d.ts
https://github.com/avajs/ava/blob/master/index.js.flow

**Comment by okyantoro** [comment]
Sure @sindresorhus

**Comment by novemberborn** [comment]
Thanks @okyantoro!

**Comment by ronen** [comment]
Thanks @okyantoro from me too!

**Pull request merged**
