### PR TITLE
Babel 7 support and additional enhancements

### LINKED ISSUE #1225: Add `ava/babel` as a shortcut for including AVA's Babel presets
It seems to be a good convention across the community (glamor, next.js, more) to provide a shortcut for auto-including Babel settings. If user wants to customize presets, right now he has to include these presets manually. What I'm proposing:

```js
{
  "presets": [
    "ava/babel",
    "custom-preset"
  ]
}
```

It would also significantly simplify the creation of tools like [ava-preact-init](https://github.com/avajs/ava-preact-init), ava-react-init, ava-inferno-init, etc. If we provide a simple entrypoint for these presets, we won't need to update each of these modules when we change something in our presets.

### LINKED ISSUE #1598: Getting ready for Babel 7
Babel 7 will be released soon (#1575). Here's what we're going to do:

* AVA will ship with Babel 7, since its test file transforms should work out of the box
* We'll update https://github.com/avajs/babel-preset-stage-4, https://github.com/avajs/babel-plugin-throws-helper and https://github.com/avajs/babel-preset-transform-test-files to ensure they work with Babel 7, update their CI configuration and release new major versions to prevent any accidental (future) breakage with older AVA releases
* I'll update https://github.com/novemberborn/hullabaloo-config-manager so it can resolve [Babel 7 configurations](https://github.com/novemberborn/hullabaloo-config-manager/issues?q=is%3Aissue+is%3Aopen+label%3Ababel7)

Any changes that are required in the dependencies will be released to npm when they're ready. The remaining changes in AVA itself will be held back until Babel 7 is officially released. We'll do a new AVA release once the dust settles. Those of you working with Babel's beta versions will be able to install from GitHub.

It's possible that AVA won't fully support all the new configuration options, but that won't stop us from releasing Babel 7 support. We'll just have to document what's still missing.

There's a lot of pieces to coordinate here, so for now I've assigned myself to this effort. If you've got some time in the next few weeks and are looking to help out, please chime in here and I'll see where we are. There's lots of [other issues labeled "help wanted"](https://github.com/avajs/ava/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) too 😉 

Thanks!

### PR DESCRIPTION
**Pull request by novemberborn**
Fixes #1598. Switches AVA's Babel implementation to use Babel 7. This applies to test and helper file compilation.

Adds a `compileEnhancements` option which can be set to `false` to disable Power Assert and our `t.throws()` helper.

Changes the Babel configuration. If you had this before:

```json
"ava": {
  "babel": {
    "plugins": []
  }
}
```

You'll now need:

```json
"ava": {
  "babel": {
    "testOptions": {
      "plugins": []
    }
  }
}
```

`ava.babel.testOptions.babelrc` now defaults to `true`. You can disable our stage-4 preset by adding `["ava/stage-4", false]` to `ava.babel.testOptions.presets`. Set `ava.babel` to `false` to disable AVA's test file compilation, **whilst still compiling enhancements**. If `compileEnhancements` is *also* set to `false` then Babel is skipped completely.

Fixes #1225, #1488 and #1556.

### CODE REVIEW

**Comment by citycide** [comment]
All seems to work so far! Was up and running using new `@babel` plugins in tests. `.babelrc.js` support is something I'm looking forward to.

**Comment by danny-andrews** [comment]
I tried to give this a whirl. I'm getting `Cannot find module 'hullabaloo-config-manager'`

**Comment by novemberborn** [comment]
@danny-andrews are you installing using npm 5.6? Currently these are Git dependencies, and `hullabaloo-config-manager` has a build step, so earlier npm versions might not handle them particularly well.

**Comment by citycide** [comment]
@novemberborn would it be premature to publish these at `@next` tags? That'd make it more accessible for testing so is that the plan now at some point?

**Comment by novemberborn** [comment]
@citycide I think so, yes. There's five dependencies that need updating, one of which we don't have control over. I haven't seen a clear timeline for when Babel 7 goes stable, and there've been significant changes over the past few weeks alone. For now let's stick to installing from this GitHub branch.

**Comment by danny-andrews** [comment]
@novemberborn I used yarn. I'll just hold off until things progress. Found a workaround to get pipeline-operator to work without upgrading to babel 7. :)

**Comment by novemberborn** [comment]
@citycide I'm hopeful that `.babelrc.js` files work now. Either through the `babelrc` option or by extending from JS files. Note that AVA does not yet take dependency changes into account if you use `require()` inside those JS configuration files.

There's a test failure in Node.js 4 in https://github.com/novemberborn/hullabaloo-config-manager/pull/25 which might just be the test itself, not the code, but I don't have the time to figure that out right now.

**Comment by novemberborn** [comment]
Also this PR now selects the `test` environment if `BABEL_ENV` and `NODE_ENV` are not set, similar to how we set `NODE_ENV` in the workers.

**Comment by citycide** [comment]
@novemberborn it works :raised_hands:

tested it on:
node v8.9.3, v6.12.2
npm v5.6.0, v3.10.10
babel v7.0.0-beta.34 w/ `@babel/preset-stage-0` ( used pipeline and nullish coalescer in test :yum: )

For others who want to test, yarn didn't install the `hullabaloo-config-manager` dependency correctly. Once I used npm it worked fine.

**Comment by novemberborn** [comment]
Please see the updated PR description.

I'll publish beta releases of our various dependencies and then merge this into `master`.

**Pull request merged**
