### PR TITLE
Docs: Extend VSCode debugging notes

### PR DESCRIPTION
**Pull request by JPeer264**
Extended the VSCode debugging instructions with `debugger;`.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Is there an open VSCode issue about the buggy breakpoints?

**Comment by JPeer264** [comment]
There are related:
- https://github.com/Microsoft/vscode/issues/8062
- https://github.com/Microsoft/vscode/issues/19973

**Comment by forresst** [comment]
french translation : done (avajs/ava-docs@87cfbdf2d0f19ad335eecfda7114f85ad446b92b)

**Pull request merged**
