### PR TITLE
Explain how to use custom HTTP clients when endpoint testing

### PR DESCRIPTION
**Pull request by tryzniak**
Some people may want to use a more familiar client to them like fetch, got and etc when endpoint testing. Let's explain how to do that!

### CODE REVIEW

**Comment by novemberborn** [comment]
Yes that's fair enough. I wonder if we should shake up this recipe a bit more. E.g. explain how to start a server in a `.before()` hook, use `test-listen` or `get-port` and share the URL via `t.context`. Then we can show an example that uses `got()` and AVA's assertions and link to tools like `supertest` at the end of the recipe.

What do you think @tryzniak?

**Comment by novemberborn** [comment]
@tryzniak I've made some edits, what do you think?

**Comment by tryzniak** [comment]
> @tryzniak I've made some edits, what do you think?

I love them :) Don't know if I can anything to it :)

**Comment by novemberborn** [comment]
@tryzniak cool, merged!

**Pull request merged**
