### PR TITLE
update to new power-assert-runtime

### LINKED ISSUE #693: Feature Request: Better error messaging for acorn parsing errors when testing React
If JSX code is inlined into a test assertion (e.g. using enzyme's .contains, etc) acorn from the power-assert library fails hard (fails hard enough to kill the `--watch` watcher):

```javascript
test("some test", t => {
    //...
    const wrapper = shallow(<Lesson {...props} />);
    t.true(wrapper.contains(<div className="page-container is-kiosk-mode" />));
});
```

```
/Users/dcousineau/Projects/frontend/node_modules/acorn/dist/acorn.js:945
  throw err;
  ^

SyntaxError: Unexpected token (1:24)
    at Parser.pp.raise (/Users/dcousineau/Projects/frontend/node_modules/acorn/dist/acorn.js:943:13)
    at Parser.pp.unexpected (/Users/dcousineau/Projects/frontend/node_modules/acorn/dist/acorn.js:1503:8)
...
```

The solution to fix this error is a very simple:

```javascript
test("some test", t => {
    //...
    const wrapper = shallow(<Lesson {...props} />);
    const actual = wrapper.contains(<div className="page-container is-kiosk-mode" />);
    t.true(actual);
});
```

It would be nice if AVA could expect and catch this error, prevent it from hard exiting the process, and possibly display messaging like "Unparseable (possibly JSX) code found in your test assertion. Try assigning the code to a variable first then running the assert against the variable".

### PR DESCRIPTION
**Pull request by nfcampos**
- should close #693, #881 and similar issues about experimental syntax breaking on assertion failure.
- it also appears to be faster than before, but not by much
- i've added two tests that assert that using JSX and `{...o}` on an assertion works

maybe @twada can check whether I correctly configured the various `power-assert` things

### CODE REVIEW

**Comment by twada** [comment]
Thanks @nfcampos! This is exactly what I wanted to do today 😃 

[babel-plugin-espower 2.2.0](https://github.com/power-assert-js/babel-plugin-espower/pull/13) and the new [power-assert-runtime](https://github.com/twada/power-assert-runtime) comes with many architectural improvements with less dependencies. I hope AVA guys will like it.

**Comment by jamestalmage** [comment]
I'm sure will!

@twada, has the runtime dependency graph been reduced? Should we move rendering back into the child processes - we've had lots of problems trying to serialize large objects for rendering in the main thread.

**Comment by twada** [comment]
> has the runtime dependency graph been reduced?

Yeah, reducing dependencies is one of the goals of new power-assert-runtime. There's no extra parser anymore. Many ponyfills are consolidated into single core-js.

I also recommend @nfcampos to update [empower-core to 0.6.1](https://github.com/twada/empower-core/blob/master/CHANGELOG.md#061-2016-06-05) to reduce dependencies much more.


> Should we move rendering back into the child processes

Yes. Now we can render power-assert output in subprocesses.

**Comment by jamestalmage** [comment]
@nfcampos. Can you bump the dependency as mentioned? Otherwise this looks good to me.

We can tackle moving rendering to the child process in another PR

**Comment by nfcampos** [comment]
done

**Comment by twada** [comment]
Thanks @nfcampos, looks good to me! 👍

**Comment by jamestalmage** [comment]
Thanks @nfcampos! Want to work on moving the renderer into the child process?

The idea is to go back to the way `power-assert` behaves in other contexts - replacing the error message on the assertion.

**Comment by nfcampos** [comment]
@jamestalmage yes, I'll do that, if I understand correctly it's something like using https://github.com/power-assert-js/empower instead of `empower-core` in `enhance-assert.js` and stop using the formatter in `run-status.js`?

**Comment by twada** [comment]
@nfcampos One thing to notice is that `empower` module is now a thin wrapper around `empower-core` for power-assert internal compatibility and there is no reason to use `empower` in AVA. It's better to keep using `empower-core` directly.

**Comment by nfcampos** [comment]
@twada yeah you're right

**Comment by jimthedev** [comment]
@nfcampos So, quick question about the ava docs and this PR, specifically in [the React recipe for JSX helpers](https://github.com/avajs/ava/blob/master/docs/recipes/react.md#using-jsx-helpers) there the following note:

> Note that you have to use variables like actual and expected because power-assert doesn't handle JSX correctly.

The text links to [this](https://github.com/power-assert-js/power-assert/issues/34) issue which although open (documentation still pending) states that it will be available in ava as soon as this PR (#903) is merged. Since #903 has been merged, do we need to remove that note from the React recipe?

**Comment by nfcampos** [comment]
yes that note should be removed, that should now work

**Pull request merged**
