### PR TITLE
docs(typescript): Updates Typescript Recipe

### LINKED ISSUE #2376: "Enhancement compilation must be configured in AVA’s Babel options" error with TypeScript.
I'm trying to run some unit tests with TypeScript using `ts-node` package as described in official ava's TS [recipe](https://github.com/avajs/ava/blob/master/docs/recipes/typescript.md).

Facing an error:
```
> node ./node_modules/ava/cli.js

  ✖ Enhancement compilation must be configured in AVA’s Babel options.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! some_package@0.0.1 test: `node ./node_modules/ava/cli.js`
npm ERR! Exit status 1
```

Node version: 13.6.0
Ava version: 3.0.0
TypeScript version: 3.7.5
OS: Linux Mint 19.1 (Tessa)
Running ava both ways leads to same result: 
`node ./node_modules/ava/cli.js` as locally installed
`ava` as globally installed.

Must note that with ava v2.4.0 everything works as expected.
Repository to reproduce: https://github.com/meyve/ava_test

### PR DESCRIPTION
**Pull request by jhechtf**
Previous iteration had configuration that is no longer necessary for version 3.

Closes #2376

### CODE REVIEW

**Comment by sindresorhus** [comment]
The recipe should only mention AVA 3. The changes can go into the release notes instead.

**Comment by jhechtf** [comment]
Alright. I'll update it to reflect that.

**Comment by novemberborn** [comment]
@jhechtf thanks for picking this up. There is one other mention of `compileEnhancements` actually.

**Comment by novemberborn** [comment]
Thanks @jhechtf!

**Pull request merged**
