### PR TITLE
cache error

### PR DESCRIPTION
**Pull request by janat08**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you elaborate? I don't think this update is correct. What kind of error did you get?

**Comment by janat08** [comment]
It's somehow gone from the terminal, but it was referring to some hashed file with map in it with cache being somewhere in dir possibly. I was following vscode recipe on ubuntu:
```
		{
			"type": "node",
			"request": "launch",
			"name": "Run AVA test",
			"program": "${workspaceFolder}/node_modules/ava/profile.js",
			"args": ["${file}",
				  "--serial"],
			"skipFiles": ["<node_internals>/**/*.js"]
		}
```

**Comment by janat08** [comment]
image

**Comment by novemberborn** [comment]
It's hard to say what caused that error, but I don't think it's something that can easily be worked around.

(I'm closing this PR for housekeeping purposes, but let's keep the conversation going.)

**Comment by janat08** [comment]
the workaround is to run tests before doing debugging.

**Pull request closed without merging**
