### PR TITLE
Type observables based on how they're consumed by AVA

### PR DESCRIPTION
**Pull request by micaelmbagira**
This PR aims to fix https://github.com/avajs/ava/issues/2212

**Description**
The following snippet breaks because of types conflict

```ts
import { of } from 'rxjs';

test('foo', t => {
  return of(3).pipe(tap(() => t.pass()));
});
```

The reasons are the following:

1. `ObservableLike` has the [Symbol.observable](https://github.com/ReactiveX/rxjs/blob/56cbd220dac11ec58751e15a23a56d6747964df2/src/internal/types.ts#L55-L57) tag 
2. the inferred type of `of(3)` is `Observable`
3. in RxJS, `Observable` [does not have the `[Symbol.observable]()` property](https://github.com/ReactiveX/rxjs/blob/56cbd220dac11ec58751e15a23a56d6747964df2/src/internal/Observable.ts#L303), so it breaks.

So ideally, [`ImplementationResult`](ImplementationResult type) type  should be [`SubscribableOrPromise`](https://github.com/ReactiveX/rxjs/blob/56cbd220dac11ec58751e15a23a56d6747964df2/src/internal/types.ts#L37)

**Solution**

- added a `SubscribableLike` interface similar to [RxJS type definitions](https://github.com/ReactiveX/rxjs/blob/56cbd220dac11ec58751e15a23a56d6747964df2/src/internal/types.ts#L37-L50) 
- the `ObserverLike` interface is also [similar to RxJS types](https://github.com/ReactiveX/rxjs/blob/56cbd220dac11ec58751e15a23a56d6747964df2/src/internal/types.ts#L84-L89) but as suggested by @novemberborn, I took the signature that is used when [ava subscribes to it](https://github.com/sindresorhus/observable-to-promise/blob/f886c9335595c1b9265a24d62825427e17fc45c2/index.js#L13)

@novemberborn I wanted to add a unit test but I would need to import `rxjs` as a devDependency, is it worth it?

### CODE REVIEW

**Comment by novemberborn** [comment]
> I wanted to add a unit test but I would need to import `rxjs` as a devDependency, is it worth it?

Yes that'd be great.



> * the `ObserverLike` interface is also [similar to RxJS types](https://github.com/ReactiveX/rxjs/blob/56cbd220dac11ec58751e15a23a56d6747964df2/src/internal/types.ts#L84-L89) but as suggested by @novemberborn, I took the signature that is used when [ava subscribes to it](https://github.com/sindresorhus/observable-to-promise/blob/f886c9335595c1b9265a24d62825427e17fc45c2/index.js#L13)

We need to replace `observable-to-promise`, since that is looking for symbols and whatnot rather than just calling `subscribe`.

**Comment by novemberborn** [comment]
> > * the `ObserverLike` interface is also [similar to RxJS types](https://github.com/ReactiveX/rxjs/blob/56cbd220dac11ec58751e15a23a56d6747964df2/src/internal/types.ts#L84-L89) but as suggested by @novemberborn, I took the signature that is used when [ava subscribes to it](https://github.com/sindresorhus/observable-to-promise/blob/f886c9335595c1b9265a24d62825427e17fc45c2/index.js#L13)
> 
> We need to replace `observable-to-promise`, since that is looking for symbols and whatnot rather than just calling `subscribe`.

I've pushed commits to address this.

> > I wanted to add a unit test but I would need to import `rxjs` as a devDependency, is it worth it?
> 
> Yes that'd be great.

We have existing tests using `zen-observable`, but I wouldn't mind another integration test for `rxjs`.

**Comment by micaelmbagira** [comment]
@novemberborn thanks. I'll try to add the `rxjs` test tomorrow

**Comment by novemberborn** [comment]
> Why v3 though? This fixes a bug introduced in v2.

It's going into the v3 release.

**Pull request merged**
