### PR TITLE
[WIP - Discuss]: Document current API design.

### PR DESCRIPTION
**Pull request by jamestalmage**
Just putting together a list of all the options we pass around, so we can start thinking about how to clean things up.

I think I see some easy wins already.

TODO's:

- [x] document the options passed down to the child process via `fork.js` (currently everything passed to the API gets serialized - but I want to develop a list of what is actually used, so we know what is getting passed around).

- [ ] document the various events we're passing around:

  - [x] events between child and fork.js

  - [ ] events between fork and api

  - [ ] events that get passed to loggers

  - [ ] ???

If anybody wants to take a peice of this, just chime in.

### CODE REVIEW

**Comment by novemberborn** [comment]
@avajs/core how interested in this are we? Clearly we've ignored this PR for 4 months now 😉  These kinds of documents are also hard to keep up to date. I'd rather we capture this stuff more clearly in the source code.

**Comment by sotojuan** [comment]
Agreed. At the very least we may do this on 1.0.

**Comment by jamestalmage** [comment]
The point was never really to merge, but to wrap my head around all the events getting passed around, and find ways to simplify it all.

Documenting in the source is fine, but not that helpful for a high level view of how everything glues together. Event transmission and reception happen all over the place.

I'm fine with closing it.

**Comment by sindresorhus** [comment]
I also think we should simplify the event transmission.

**Pull request closed without merging**
