### PR TITLE
Recipe: precompile, code coverage, auto-reload of coverage

### PR DESCRIPTION
**Pull request by lordfuoco**
A simple recipe to ( trough npm scripts ) achieve:

1. Run all your test when your test AND/OR source file changes
1. Compile your source file with babel
1. Output the coverage of your tests
1. Display the HTML report of your coverage
1. Live Reload your coverage so that is possible to see the lines hit by the tests

### CODE REVIEW

**Comment by novemberborn** [comment]
@lordfuoco this is a very nice approach!

I'm not sure if your setup can be generalized enough for this to be a recipe. E.g. the shell scripts are quite particular (and won't work on Windows). Then there's the dependency on `yarn`.

Perhaps this would work best as a blog post where you explain how you tackled this problem. We can link to it from the [Code coverage recipe](https://github.com/avajs/ava/blob/master/docs/recipes/code-coverage.md) as well as https://github.com/avajs/awesome-ava/.

What do you think?

**Comment by lordfuoco** [comment]
We can easily remove yarn dependency by switching to npm, but sure a blog post is cool, I will try to scavenge some time to make it (not sure how but will try)

**Comment by novemberborn** [comment]
Hey @lordfuoco I hope you don't mind me closing this PR. Am still looking forward to seeing this as a blog post, please let me know if I can help with that.

**Comment by lordfuoco** [comment]
Hi Mark,

Sure I do not mind, I will write the blog post when I have some time! and
post it here!

**Pull request closed without merging**
