### PR TITLE
Experimentally reverse teardown order

### PR DESCRIPTION
**Pull request by yjpa7145**
When enabled, teardown functions will be run in the reverse order that they were declared.

Addresses avajs/ava#2495 - Add ability to reverse the order of teardown
steps

### CODE REVIEW

**Comment by novemberborn** [comment]
Looks great @yjpa7145!

Would you mind having a go at adding some documentation for this to https://github.com/avajs/ava/blob/master/docs/02-execution-context.md#tteardownfn?

**Comment by yjpa7145** [comment]
> Would you mind having a go at adding some documentation for this

Done: 5d95ed9

**Comment by novemberborn** [comment]
Something came up and I haven’t yet had a chance to look at this again.

**Comment by novemberborn** [comment]
Thanks @yjpa7145! I've opened https://github.com/avajs/ava/issues/2516 to make this official in v4.

**Pull request merged**
