### PR TITLE
Add recipe docs for t.context (#1730)

### PR DESCRIPTION
**Pull request by Seiyial**
Recipe detailing context in per-file and per-test hooks #1730

### CODE REVIEW

**Comment by novemberborn** [comment]
Hi @Seiyial, thanks for your PR. I've been busy lately so it may take a bit longer before I can properly look at this.

**Comment by Seiyial** [comment]
Hi @novemberborn , sorry I missed the notification.

By assertions do you mean `t.deepEqual()` etc? I personally thought of using `console.log()` because the readers may not yet be familiarised with ava's syntax. But come to think of it, the assert syntax looks quite foolproof so I guess using assert statements might be better.

Oh I see, that sounds important. I'll guess I should highlight that in too.

**Comment by novemberborn** [comment]
> By assertions do you mean t.deepEqual() etc? I personally thought of using console.log() because the readers may not yet be familiarised with ava's syntax. But come to think of it, the assert syntax looks quite foolproof so I guess using assert statements might be better.

Yes. People will have to learn those assertions at some point, so I'd rather the examples are close to actual use cases rather than simplified.

**Comment by novemberborn** [comment]
Hey @Seiyial are you still interested in working on this?

**Comment by Seiyial** [comment]
Hi @novemberborn , sorry for the late reply again. I have been busy and will be busier in the coming weeks, so it may be considerable if someone else is free to do it faster. That being said, I've updated the recipe in `docs/recipes/context.md` based on your comments in this thread, including changing `console.log` to assertions and adding `test.afterEach.always()` to the diagram. The shallow cloning is also highlighted with examples.

Thanks for looking through it!

Just in case the diagram still needs editing and someone else is taking it, the raw version is here: [https://bit.ly/2IWsSbL](https://bit.ly/2IWsSbL)

**Comment by sindresorhus** [comment]
@Seiyial Still interested in finishing this? :)

**Comment by Seiyial** [comment]
Sure! Am freer now. Please let me know if it needs any more changes, thanks!

**Comment by novemberborn** [comment]
Heya @Seiyial. I just reread the [Test context](https://github.com/avajs/ava#test-context) section in the README. I think it describes the behavior quite succinctly. Perhaps the recipe could start by repeating that section?

Then for the examples, we should have one example that modifies of `t.context` properties, and a second example that modifies a nested object (which isn't cloned). Both examples should use all hooks.

What do you think?

**Comment by sindresorhus** [comment]
Ping @Seiyial :)

**Comment by Seiyial** [comment]
@sindresorhus so sorry I got busy halfway! But as discussed at #1730 @mh81 has picked this up and is working on it now :)

**Comment by novemberborn** [comment]
Thanks @Seiyial. I'm closing this issue for housekeeping purposes.

**Pull request closed without merging**
