### PR TITLE
Convert integration tests to be self-hosted

### PR DESCRIPTION
**Pull request by jonathansamines**
Integration tests related to configuration options were migrated:

- [Concurrency options](https://github.com/avajs/ava/blob/master/test-tap/integration/concurrency.js)
- [Line number selection](https://github.com/avajs/ava/blob/master/test-tap/integration/line-numbers.js)
- [Node arguments](https://github.com/avajs/ava/blob/master/test-tap/integration/node-arguments.js)
- [Ava configuration](https://github.com/avajs/ava/blob/master/test-tap/integration/config.js)
- [Environment variables](https://github.com/avajs/ava/blob/master/test-tap/integration/environment-variables.js)
- [File extensions](https://github.com/avajs/ava/blob/master/test-tap/integration/extensions.js)
- [Globs](https://github.com/avajs/ava/blob/master/test-tap/integration/globs.js)

### CODE REVIEW

**Comment by jonathansamines** [comment]
@novemberborn This is ready for review, if you have some time to spare

**Comment by novemberborn** [comment]
Nice! And CodeCov is happy too.

What do you think of using snapshots, especially for error messages? Not a biggie if you don't think that's worthwhile we can merge this as-is.

**Comment by jonathansamines** [comment]
@novemberborn Updated all tests to use snapshot testing. Also, thanks for fixing the issue on Node 14 ;)

**Comment by novemberborn** [comment]
Fantastic thank you so much @jonathansamines ❤️

**Pull request merged**
