### PR TITLE
Flow type definition for snapshot assertion #1245

### PR DESCRIPTION
**Pull request by LasaleFamine**
The work should be the same of #1243

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please see https://github.com/avajs/ava/pull/1243#discussion_r100118036.

**Comment by LasaleFamine** [comment]
Sorry, I missed it.

**Comment by novemberborn** [comment]
Sorry, this one is Flow, not TypeScript :)

**Comment by novemberborn** [comment]
Thanks @LasaleFamine!

**Pull request merged**
