### PR TITLE
Assertions return boolean

### PR DESCRIPTION
**Pull request by adiSuper94**
Changes to address #2455 .
Assertion return boolean.

### CODE REVIEW

**Comment by adiSuper94** [comment]
@novemberborn if the way I have edited the assertion testcases are fine, I'll make the changes to all cases.

**Comment by novemberborn** [comment]
> if the way I have edited the assertion testcases are fine, I'll make the changes to all cases.

Does this include the changes made in #2564? Would you be able to edit the commits here so that de1625816b740093558bb8514826eda56ab810ef is included, followed by your changes? It'll make it easier to see what you've addressed from #2564 and it retains the credit.

**Comment by adiSuper94** [comment]
@novemberborn  rebaseing  [de16258](https://github.com/avajs/ava/commit/de1625816b740093558bb8514826eda56ab810ef) have updated all the commits after that too as a side effect.
Closing this merge request.
Please check this one out #2586

**Comment by adiSuper94** [comment]
> > if the way I have edited the assertion testcases are fine, I'll make the changes to all cases.
> 
> Does this include the changes made in #2564? Would you be able to edit the commits here so that [de16258](https://github.com/avajs/ava/commit/de1625816b740093558bb8514826eda56ab810ef) is included, followed by your changes? It'll make it easier to see what you've addressed from #2564 and it retains the credit.

I didn't start working on top of [de16258], but there are some changes which are common, so I have rebased to give give due credit.

**Pull request closed without merging**
